// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relay.Domain;
using Relay.Infrastructure;

#nullable disable

namespace Relay.Infrastructure.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    partial class RelayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "outcome_polarity", "outcome_polarity", new[] { "good", "bad", "neutral" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relay.Infrastructure.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.AccountDashboardSettings", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("AmberFraction")
                        .HasColumnType("numeric")
                        .HasColumnName("amber_fraction");

                    b.Property<int>("DefaultComparisonWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("default_comparison_weeks");

                    b.Property<int>("MinBaselineEvents")
                        .HasColumnType("integer")
                        .HasColumnName("min_baseline_events");

                    b.Property<int>("MinHistoryWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("min_history_weeks");

                    b.Property<int>("MinRateDenominator")
                        .HasColumnType("integer")
                        .HasColumnName("min_rate_denominator");

                    b.Property<decimal>("MinWeekCompleteness")
                        .HasColumnType("numeric")
                        .HasColumnName("min_week_completeness");

                    b.Property<decimal>("TolerancePct")
                        .HasColumnType("numeric")
                        .HasColumnName("tolerance_pct");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("pk_account_dashboard_settings");

                    b.ToTable("account_dashboard_settings", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.HasKey("Id")
                        .HasName("pk_activity_events");

                    b.ToTable("activity_events", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.DataQualityExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id")
                        .HasName("pk_data_quality_exclusions");

                    b.ToTable("data_quality_exclusions", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.EventTypeCatalog", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Code")
                        .HasName("pk_event_type_catalog");

                    b.ToTable("event_type_catalog", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.IsoWeek", b =>
                {
                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.Property<int>("IsoWeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iso_week_number");

                    b.Property<int>("IsoYear")
                        .HasColumnType("integer")
                        .HasColumnName("iso_year");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.HasKey("WeekStart")
                        .HasName("pk_iso_weeks");

                    b.ToTable("iso_weeks", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_account_id_name");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.OutcomeCatalog", b =>
                {
                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<OutcomePolarity>("Polarity")
                        .HasColumnType("outcome_polarity")
                        .HasColumnName("polarity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("EventType", "Code")
                        .HasName("pk_outcome_catalog");

                    b.ToTable("outcome_catalog", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Entities.WeeklyActivityFact", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("DaysIncluded")
                        .HasColumnType("integer")
                        .HasColumnName("days_included");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("ExpectedDays")
                        .HasColumnType("integer")
                        .HasColumnName("expected_days");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateOnly>("WeekStartLocal")
                        .HasColumnType("date")
                        .HasColumnName("week_start_local");

                    b.ToTable((string)null);

                    b.ToView("weekly_activity_facts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
