using Npgsql;
using Relay.Domain;

namespace Relay.Tests.Integration;

/// <summary>
/// Requirements §4 "Timezone and week boundaries" — the DB half: the account-timezone conversion
/// SQL in <c>activity_events_local</c> (06_activity_events_local.sql), and the real
/// <c>iso_weeks</c> spine generated from this seed around the 2026-03-08 DST transition. The pure
/// half (DateOnly-only ISO week arithmetic) lives in <c>WeekRangeTests</c>.
/// </summary>
[Collection(SeededDatabaseCollection.Name)]
public class TimezoneBoundaryTests(SeededDatabaseFixture fixture)
{
    [Fact]
    public async Task EventLateMondayUtc_ForLosAngelesAccount_FallsOnThePreviousLocalDay_AndPreviousIsoWeek()
    {
        // Uses the exact conversion expression 06_activity_events_local.sql applies to every row
        // (`occurred_at AT TIME ZONE 'UTC' AT TIME ZONE a.timezone`), against a literal timestamp
        // and account 20's real timezone column — not an inserted row, so the seed stays untouched.
        // 2026-03-16 04:00 UTC (a Monday) is 2026-03-15 21:00 in America/Los_Angeles (UTC-7, PDT —
        // already in effect a week after the 2026-03-08 "spring forward" transition): the local
        // calendar day rolls back across midnight to a Sunday, one calendar day and one ISO week
        // behind the UTC timestamp's own date.
        await using var connection = await fixture.OpenConnectionAsync();
        await using var command = new NpgsqlCommand(
            """
            SELECT
                (TIMESTAMP '2026-03-16 04:00:00' AT TIME ZONE 'UTC' AT TIME ZONE a.timezone)::date AS local_date,
                extract(isodow FROM (TIMESTAMP '2026-03-16 04:00:00' AT TIME ZONE 'UTC' AT TIME ZONE a.timezone))::int AS local_isodow
            FROM accounts a
            WHERE a.id = 20
            """,
            connection);
        await using var reader = await command.ExecuteReaderAsync();
        await reader.ReadAsync();

        var localDate = reader.GetFieldValue<DateOnly>(0);
        var localIsoDow = reader.GetInt32(1);

        Assert.Equal(new DateOnly(2026, 3, 15), localDate); // the previous local day
        Assert.Equal(7, localIsoDow); // Sunday

        var utcCalendarWeek = WeekRange.Containing(new DateOnly(2026, 3, 16)); // 2026-W12
        var localCalendarWeek = WeekRange.Containing(localDate); // 2026-W11

        Assert.NotEqual(utcCalendarWeek.Start, localCalendarWeek.Start); // the previous ISO week
        Assert.Equal(localCalendarWeek.Start, localCalendarWeek.Next().Start.AddDays(-7));
    }

    [Fact]
    public async Task IsoWeeksSpine_AroundThe20260308DstTransition_HasNoSixOrEightDayWeek()
    {
        // iso_weeks is generated by 07_iso_weeks.sql from this seed's real local_date range, which
        // spans the 2026-03-08 US "spring forward" transition. WeekRangeTests already proves
        // WeekRange itself cannot produce a malformed week (it is DateOnly-only); this proves the
        // SQL spine the app actually reads from doesn't either, for the two real weeks either side
        // of the transition date.
        await using var db = fixture.CreateDbContext();

        var weeks = db.IsoWeeks
            .Where(w => w.WeekStart >= new DateOnly(2026, 2, 23) && w.WeekStart <= new DateOnly(2026, 3, 16))
            .OrderBy(w => w.WeekStart)
            .ToList();

        Assert.Equal(4, weeks.Count); // 2026-02-23, 2026-03-02 (contains the DST Sunday), 2026-03-09, 2026-03-16

        foreach (var week in weeks)
        {
            Assert.Equal(6, week.WeekEnd.DayNumber - week.WeekStart.DayNumber); // exactly 7 days, never 6 or 8
        }

        for (var i = 1; i < weeks.Count; i++)
        {
            Assert.Equal(7, weeks[i].WeekStart.DayNumber - weeks[i - 1].WeekStart.DayNumber); // gapless
        }
    }

    [Fact]
    public async Task IsoWeeksSpine_IsGaplessAcrossTheWholeFirstToLatestRange()
    {
        // EfDashboardReader trusts iso_weeks to be gapless across [firstWeek, latestWeekWithData]
        // and turns a gap into a diagnosed InvalidOperationException rather than an unexplained
        // 500 — but the gaplessness itself is 07_iso_weeks.sql's job to get right, and this is
        // Stage 3's proof of it, independent of sql/verify_migration.sql's hand-run version.
        await using var db = fixture.CreateDbContext();

        var weekStarts = db.IsoWeeks.OrderBy(w => w.WeekStart).Select(w => w.WeekStart).ToList();

        Assert.Equal(27, weekStarts.Count);
        Assert.Equal(new DateOnly(2026, 1, 26), weekStarts[0]);
        Assert.Equal(new DateOnly(2026, 7, 27), weekStarts[^1]);

        for (var i = 1; i < weekStarts.Count; i++)
        {
            Assert.Equal(7, weekStarts[i].DayNumber - weekStarts[i - 1].DayNumber);
        }
    }
}
