<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Relay.Application\Relay.Application.csproj" />
    <ProjectReference Include="..\Relay.Infrastructure\Relay.Infrastructure.csproj" />
  </ItemGroup>

</Project>
