-- Additive tables (PLAN.md § Migration 001 — detail, step 2). All IF NOT EXISTS: this file must
-- be silently re-runnable both by EF's migration history and by a reviewer running it by hand.
-- Types generated by `dotnet ef migrations add` against the current model (PLAN.md Open Question
-- 10), then moved here so Up() stays uniformly migrationBuilder.Sql().

CREATE TABLE IF NOT EXISTS locations (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  integer NOT NULL REFERENCES accounts (id),
    name        text NOT NULL,
    opened_on   date,
    closed_on   date,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_locations_account_id_name
    ON locations (account_id, name);

CREATE TABLE IF NOT EXISTS event_type_catalog (
    code         text PRIMARY KEY,
    display_name text NOT NULL,
    sort_order   integer NOT NULL
);

CREATE TABLE IF NOT EXISTS outcome_catalog (
    event_type   text NOT NULL REFERENCES event_type_catalog (code),
    code         text NOT NULL,
    display_name text NOT NULL,
    polarity     outcome_polarity NOT NULL,
    sort_order   integer NOT NULL,
    PRIMARY KEY (event_type, code)
);

CREATE TABLE IF NOT EXISTS account_dashboard_settings (
    account_id                integer PRIMARY KEY REFERENCES accounts (id),
    default_comparison_weeks integer NOT NULL,
    tolerance_pct             numeric NOT NULL,
    min_baseline_events       integer NOT NULL,
    min_rate_denominator      integer NOT NULL,
    min_history_weeks         integer NOT NULL,
    min_week_completeness     numeric NOT NULL,
    amber_fraction            numeric NOT NULL,
    updated_at                timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS data_quality_exclusions (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  integer REFERENCES accounts (id),
    location    text,
    event_type  text,
    from_date   date NOT NULL,
    to_date     date NOT NULL,
    reason      text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS iso_weeks (
    week_start      date PRIMARY KEY,
    week_end        date NOT NULL,
    iso_year        integer NOT NULL,
    iso_week_number integer NOT NULL
);
